/** @file********************************************************************
 *
 *       Module:    physical.h
 *      Program:    SIlib2
 *   Created by:    Darren Muff on 19/07/2013.
 *                  Copyright (c) 2013 [dstl]. All rights reserved.
 *
 *   Description:
 *      SIPC - Scientific Intelligcen Physical Constants
 *      Header file containing basic physical definitions and values.
 *      Modified from the c++ version found at:
 *      http://bytes.com/topic/c/answers/135205-physical-constants-header-file
 *      Unfortunately C does not have scope so I have created around 800 
 *      independent #define parameters.
 *      eg: 
 *          double distance     = 100 * SIPC_meters ;
 *          double time         = 10 * SIPC_seconds ;
 *          double mpersec      = distance / time ;
 *          double speedInKnots = mpersec / SIPC_knot ;
 *          double speedInmph   = mpersec / SIPC_mph  ;
 *
 *   CLASSIFICATION        :  UNCLASSIFIED
 *   Date of CLASSN        :  19/07/2013
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * THE SOFTWARE IN ITS ENTIRETY OR ANY SUBSTANTIAL PORTION SHOULD NOT BE
 * USED AS A WHOLE OR COMPONENT PART OF DERIVATIVE SOFTWARE THAT IS BEING
 * SOLD TO THE GOVERNMENT OF THE UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN
 * IRELAND.
 *
 ***************************************************************************/ 

#ifndef SILib2__PHYSICS_H_
#define SILib2__PHYSICS_H_

#define	 SIPC_radian                        ((double)  1.0)
#define	 SIPC_radians                       ((double)  SIPC_radian)
#define	 SIPC_rad                           ((double)  SIPC_radian)
#define	 SIPC_steradian                     ((double)  1.0)
#define	 SIPC_steradians                    ((double)  SIPC_steradian)
#define	 SIPC_sr                            ((double)  SIPC_steradian)
#define	 SIPC_dozen                         ((double)  12.0)
#define	 SIPC_doz                           ((double)  SIPC_dozen)
#define	 SIPC_dz                            ((double)  SIPC_dozen)
#define	 SIPC_bakers_dozen                  ((double)  13.0)
#define	 SIPC_bakers_doz                    ((double)  SIPC_bakers_dozen)
#define	 SIPC_bakers_dz                     ((double)  SIPC_bakers_dozen)
#define	 SIPC_gross                         ((double)  12.0*SIPC_dozen)
#define	 SIPC_gro                           ((double)  SIPC_gross)
#define	 SIPC_quire                         ((double)  25.0)
#define	 SIPC_quires                        ((double)  SIPC_quire)
#define	 SIPC_ream                          ((double)  500.0)
#define	 SIPC_reams                         ((double)  SIPC_ream)
#define	 SIPC_percent                       ((double)  1.0/100.0)
#define	 SIPC_proof                         ((double)  SIPC_percent/2.0)
#define	 SIPC_karat                         ((double)  1.0/24.0)
#define	 SIPC_karats                        ((double)  SIPC_karat)
#define	 SIPC_mole                          ((double)  6.0221367e+23)
#define	 SIPC_moles                         ((double)  SIPC_mole)
#define	 SIPC_mol                           ((double)  SIPC_mole)
#define	 SIPC_pi                            ((double)  3.14159265358979323846*SIPC_radians)
#define	 SIPC_degree                        ((double)  SIPC_pi/180.0)
#define	 SIPC_degrees                       ((double)  SIPC_degree)
#define	 SIPC_arc_minute                    ((double)  SIPC_degree/60.0)
#define	 SIPC_arc_minutes                   ((double)  SIPC_arc_minute)
#define	 SIPC_arc_min                       ((double)  SIPC_arc_minute)
#define	 SIPC_arc_second                    ((double)  SIPC_arc_minute/60.0)
#define	 SIPC_arc_seconds                   ((double)  SIPC_arc_second)
#define	 SIPC_arc_sec                       ((double)  SIPC_arc_second)
#define	 SIPC_grade                         ((double)  0.9*SIPC_degrees)
#define	 SIPC_grad                          ((double)  SIPC_grade)
#define	 SIPC_grads                         ((double)  SIPC_grade)
#define	 SIPC_grades                        ((double)  SIPC_grade)
#define	 SIPC_centesimal_minute             ((double)  SIPC_grade/100.0)
#define	 SIPC_centesimal_minutes            ((double)  SIPC_centesimal_minute)
#define	 SIPC_centesimal_min                ((double)  SIPC_centesimal_minute)
#define	 SIPC_centesimal_second             ((double)  SIPC_grade/10000.0)
#define	 SIPC_centesimal_seconds            ((double)  SIPC_centesimal_second)
#define	 SIPC_centesimal_sec                ((double)  SIPC_centesimal_second)

/// SI units (mks)
/// length
#define	 SIPC_meter                         ((double)  1.0)
#define	 SIPC_meters                        ((double)  SIPC_meter)
#define	 SIPC_m                             ((double)  SIPC_meter)
#define	 SIPC_kilometer                     ((double)  1000.0*SIPC_meters)
#define	 SIPC_kilometers                    ((double)  SIPC_kilometer)
#define	 SIPC_km                            ((double)  SIPC_kilometer)
#define	 SIPC_decimeter                     ((double)  SIPC_meters/10.0)
#define	 SIPC_decimeters                    ((double)  SIPC_decimeter)
#define	 SIPC_dm                            ((double)  SIPC_decimeter)
#define	 SIPC_centimeter                    ((double)  SIPC_meters/100.0)
#define	 SIPC_centimeters                   ((double)  SIPC_centimeter)
#define	 SIPC_cm                            ((double)  SIPC_centimeter)
#define	 SIPC_millimeter                    ((double)  SIPC_meters/1000.0)
#define	 SIPC_millimeters                   ((double)  SIPC_millimeter)
#define	 SIPC_mm                            ((double)  SIPC_millimeter)
#define	 SIPC_micron                        ((double)  SIPC_meter/1000000.0)
#define	 SIPC_microns                       ((double)  SIPC_micron)
#define	 SIPC_nanometer                     ((double)  SIPC_meter/1000000000.0)
#define	 SIPC_nanometers                    ((double)  SIPC_nanometer)
#define	 SIPC_n                             ((double)  SIPC_nanometer)
#define	 SIPC_decinanometer                 ((double)  SIPC_meter/10000000000.0)
#define	 SIPC_decinanometers                ((double)  SIPC_decinanometer)
#define	 SIPC_Angstrom                      ((double)  SIPC_decinanometer)
#define	 SIPC_Angstroms                     ((double)  SIPC_Angstrom)
#define	 SIPC_Xunit                         ((double)  1.00202e-13*SIPC_meters)
#define	 SIPC_Xunits                        ((double)  SIPC_Xunit)
#define	 SIPC_Fermi                         ((double)  SIPC_meter/1000000000000000.0)
#define	 SIPC_Fermis                        ((double)  SIPC_Fermi)
/// area
#define	 SIPC_hectare                       ((double)  10000.0*SIPC_meter*SIPC_meter)
#define	 SIPC_hectares                      ((double)  SIPC_hectare)
#define	 SIPC_ha                            ((double)  SIPC_hectare)
/// volume
#define	 SIPC_stere                         ((double)  SIPC_meter*SIPC_meter*SIPC_meter)
#define	 SIPC_steres                        ((double)  SIPC_stere)
#define	 SIPC_liter                         ((double)  SIPC_stere/1000.0)
#define	 SIPC_liters                        ((double)  SIPC_liter)
#define	 SIPC_l                             ((double)  SIPC_liter)
#define	 SIPC_milliliter                    ((double)  SIPC_stere/1000000.0)
#define	 SIPC_milliliters                   ((double)  SIPC_milliliter)
#define	 SIPC_ml                            ((double)  SIPC_milliliter)
#define	 SIPC_cc                            ((double)  SIPC_milliliter)
#define	 SIPC_displacement_ton              ((double)  SIPC_stere)
#define	 SIPC_displacement_tons             ((double)  SIPC_displacement_ton)
#define	 SIPC_displacement_t                ((double)  SIPC_displacement_ton)
/// mass
#define	 SIPC_kilogram                      ((double)  1.0)
#define	 SIPC_kilograms                     ((double)  SIPC_kilogram)
#define	 SIPC_kg                            ((double)  SIPC_kilogram)
#define	 SIPC_quintal                       ((double)  100.0*SIPC_kilograms)
#define	 SIPC_quintals                      ((double)  SIPC_quintal)
#define	 SIPC_doppelzentner                 ((double)  SIPC_quintal)
#define	 SIPC_doppelzentners                ((double)  SIPC_doppelzentner)
#define	 SIPC_gram                          ((double)  SIPC_kilograms/1000.0)
#define	 SIPC_grams                         ((double)  SIPC_gram)
#define	 SIPC_milligram                     ((double)  SIPC_kilogram/1000000.0)
#define	 SIPC_milligrams                    ((double)  SIPC_milligram)
#define	 SIPC_mg                            ((double)  SIPC_milligram)
#define	 SIPC_metric_carat                  ((double)  SIPC_gram/5.0)
#define	 SIPC_metric_carats                 ((double)  SIPC_metric_carat)
#define	 SIPC_metric_ton                    ((double)  1000.0*SIPC_kilograms)
#define	 SIPC_metric_tons                   ((double)  SIPC_metric_ton)
#define	 SIPC_metric_t                      ((double)  SIPC_metric_ton)
/// time
#define	 SIPC_second                        ((double)  1.0)
#define	 SIPC_seconds                       ((double)  SIPC_second)
#define	 SIPC_sec                           ((double)  SIPC_second)
#define	 SIPC_s                             ((double)  SIPC_second)
#define	 SIPC_millisecond                   ((double)  SIPC_second/1000.0)
#define	 SIPC_milliseconds                  ((double)  SIPC_millisecond)
#define	 SIPC_ms                            ((double)  SIPC_millisecond)
#define	 SIPC_microsecond                   ((double)  SIPC_second/1000000.0)
#define	 SIPC_microseconds                  ((double)  SIPC_microsecond)
#define	 SIPC_us                            ((double)  SIPC_microsecond)
#define	 SIPC_nanosecond                    ((double)  SIPC_second/1000000000.0)
#define	 SIPC_nanoseconds                   ((double)  SIPC_nanosecond)
#define	 SIPC_picosecond                    ((double)  SIPC_second/1000000000000.0)
#define	 SIPC_picoseconds                   ((double)  SIPC_picosecond)
#define	 SIPC_minute                        ((double)  60.0*SIPC_seconds)
#define	 SIPC_minutes                       ((double)  SIPC_minute)
#define	 SIPC_min                           ((double)  SIPC_minute)
#define	 SIPC_hour                          ((double)  60.0*SIPC_minutes)
#define	 SIPC_hours                         ((double)  SIPC_hour)
#define	 SIPC_hr                            ((double)  SIPC_hour)
#define	 SIPC_day                           ((double)  24.0*SIPC_hours)
#define	 SIPC_days                          ((double)  SIPC_day)
#define	 SIPC_da                            ((double)  SIPC_day)
#define  SIPC_sidereal_day                  ((double) 23.9344696*SIPC_hours)
#define	 SIPC_week                          ((double)  7.0*SIPC_days)
#define	 SIPC_weeks                         ((double)  SIPC_week)
#define	 SIPC_fortnight                     ((double)  2.0*SIPC_weeks)
#define	 SIPC_fortnights                    ((double)  SIPC_fortnight)
#define	 SIPC_year                          ((double)  365.2421896698*SIPC_days)
#define	 SIPC_years                         ((double)  SIPC_year)
#define	 SIPC_yr                            ((double)  SIPC_year)
#define	 SIPC_month                         ((double)  SIPC_year/12.0)
#define	 SIPC_months                        ((double)  SIPC_month)
#define	 SIPC_mo                            ((double)  SIPC_month)
#define	 SIPC_decade                        ((double)  10.0*SIPC_years)
#define	 SIPC_decades                       ((double)  SIPC_decade)
#define	 SIPC_century                       ((double)  100.0*SIPC_years)
#define	 SIPC_centuries                     ((double)  SIPC_century)
#define	 SIPC_millenium                     ((double)  1000.0*SIPC_years)
#define	 SIPC_millenia                      ((double)  SIPC_millenium)
/// temporal frequency
#define	 SIPC_Hertz                         ((double)  1.0/SIPC_second)
#define	 SIPC_Hz                            ((double)  SIPC_Hertz)
#define	 SIPC_kiloHertz                     ((double)  1000.0*SIPC_Hertz)
#define	 SIPC_kHz                           ((double)  SIPC_kiloHertz)
#define	 SIPC_megaHertz                     ((double)  1000000*SIPC_Hertz)
#define	 SIPC_MHz                           ((double)  SIPC_megaHertz)
/// spacial frequency
#define	 SIPC_diopter                       ((double)  1.0/SIPC_meter)
#define	 SIPC_diopters                      ((double)  SIPC_diopter)
/// speed
#define	 SIPC_kph                           ((double)  SIPC_kilometers/SIPC_hour)
/// radioactivity
#define	 SIPC_Becquerel                     ((double)  1.0/SIPC_second)
#define	 SIPC_Becquerels                    ((double)  SIPC_Becquerel)
#define	 SIPC_Bq                            ((double)  SIPC_Becquerel)
#define	 SIPC_Rutherford                    ((double)  1000000.0*SIPC_Becquerels)
#define	 SIPC_Rutherfords                   ((double)  SIPC_Rutherford)
#define	 SIPC_Curie                         ((double)  3.7e+10*SIPC_Becquerels)
#define	 SIPC_Curies                        ((double)  SIPC_Curie)
#define	 SIPC_Ci                            ((double)  SIPC_Curie)
/// force
#define	 SIPC_Newton                        ((double)  SIPC_kilogram*SIPC_meter/(SIPC_second*SIPC_second))
#define	 SIPC_Newtons                       ((double)  SIPC_Newton)
#define	 SIPC_N                             ((double)  SIPC_Newton)
#define	 SIPC_dyne	                        ((double)  SIPC_Newton/100000.0)
#define	 SIPC_dynes	                        ((double)  SIPC_dyne)
#define	 SIPC_dyn	                        ((double)  SIPC_dyne)
/// pressure
#define	 SIPC_Pascal	                    ((double)  SIPC_Newton/(SIPC_meter*SIPC_meter))
#define	 SIPC_Pascals	                    ((double)  SIPC_Pascal)
#define	 SIPC_Pa	                        ((double)  SIPC_Pascal)
#define	 SIPC_Barie	                        ((double)  SIPC_Pascal/10.0)
#define	 SIPC_Baries	                    ((double)  SIPC_Barie)
#define	 SIPC_Barye	                        ((double)  SIPC_Barie)
#define	 SIPC_Baryes	                    ((double)  SIPC_Barye)
#define	 SIPC_pieze	                        ((double)  1000.0*SIPC_Pascals)
#define	 SIPC_piezes	                    ((double)  SIPC_pieze)
#define	 SIPC_pz	                        ((double)  SIPC_pieze)
#define	 SIPC_bar	                        ((double)  10000.0*SIPC_Pascals)
#define	 SIPC_bars	                        ((double)  SIPC_bar)
#define	 SIPC_Torr	                        ((double)  133.3224*SIPC_Pascals)
#define	 SIPC_atmosphere	                ((double)  760.0*SIPC_Torr)
#define	 SIPC_atmospheres	                ((double)  SIPC_atmosphere)
#define	 SIPC_atm	                        ((double)  SIPC_atmosphere)
/// energy
#define	 SIPC_Joule	                        ((double)  SIPC_Newton*SIPC_meter)
#define	 SIPC_Joules	                    ((double)  SIPC_Joule)
#define	 SIPC_J                             ((double)  SIPC_Joule)
#define	 SIPC_erg	                        ((double)  SIPC_Joule/10000000.0)
#define	 SIPC_ergs	                        ((double)  SIPC_erg)
#define	 SIPC_kiloWatthour	                ((double)  3600000.0*SIPC_Joules)
#define	 SIPC_kiloWatthours	                ((double)  SIPC_kiloWatthour)
#define	 SIPC_kWh	                        ((double)  SIPC_kiloWatthour)
/// power
#define	 SIPC_Watt	                        ((double)  SIPC_Joule/SIPC_second)
#define	 SIPC_Watts	                        ((double)  SIPC_Watt)
#define	 SIPC_W                             ((double)  SIPC_Watt)
#define	 SIPC_kiloWatt                      ((double)  1000.0*SIPC_Watts)
#define	 SIPC_kiloWatts                     ((double)  SIPC_kiloWatt)
#define	 SIPC_kW	                        ((double)  SIPC_kiloWatt)
#define	 SIPC_megaWatt                      ((double)  1000000.0*SIPC_Watts)
#define	 SIPC_megaWatts                     ((double)  SIPC_megaWatt)
#define	 SIPC_MW	                        ((double)  SIPC_megaWatt)
#define	 SIPC_milliWatt                     ((double)  SIPC_Watt/1000.0)
#define	 SIPC_milliWatts	                ((double)  SIPC_milliWatt)
#define	 SIPC_mW	                        ((double)  SIPC_milliWatt)
/// energy
#define	 SIPC_dose_Gray	                    ((double)  SIPC_Joule/SIPC_kilogram)
#define	 SIPC_dose_Grays	                ((double)  SIPC_dose_Gray)
#define	 SIPC_dose_Gy	                    ((double)  SIPC_dosedose__Gray)
#define	 SIPC_dose_Sievert	                ((double)  SIPC_Gray)
#define	 SIPC_dose_Sieverts	                ((double)  SIPC_Sieverts)
#define	 SIPC_dose_rad	                    ((double)  SIPC_dose_Gray/100.0)
#define	 SIPC_dose_rads	                    ((double)  SIPC_dose_rad)
#define	 SIPC_dose_rd                       ((double)  SIPC_dose_rad)
/// electrical current
#define	 SIPC_Ampere	                    ((double)  1.0)
#define	 SIPC_Amperes	                    ((double)  SIPC_Ampere)
#define	 SIPC_A                             ((double)  SIPC_Ampere)
#define	 SIPC_Biot	                        ((double)  10.0*SIPC_Amperes)
#define	 SIPC_Biots	                        ((double)  SIPC_Biot)
/// electrical potential
#define	 SIPC_Volt	                        ((double)  SIPC_Watt/SIPC_Ampere)
#define	 SIPC_Volts	                        ((double)  SIPC_Volt)
#define	 SIPC_V                             ((double)  SIPC_Volt)
/// electrical resistance
#define	 SIPC_Ohm	                        ((double)  SIPC_Volt/SIPC_Ampere)
#define	 SIPC_Ohms	                        ((double)  SIPC_Ohm)
/// electrical conductance
#define	 SIPC_mho	                        ((double)  1.0/SIPC_Ohm)
#define	 SIPC_mhos	                        ((double)  SIPC_mho)
#define	 SIPC_Siemens	                    ((double)  SIPC_mho)
#define	 SIPC_S                             ((double)  SIPC_Siemens)
/// elsectrical charge
#define	 SIPC_Coulomb                       ((double)  SIPC_Ampere*SIPC_second)
#define	 SIPC_Coulombs                      ((double)  SIPC_Coulomb)
#define	 SIPC_C                             ((double)  SIPC_Coulomb)
#define	 SIPC_Franklin                      ((double)  3.33564e-10*SIPC_Coulombs)
#define	 SIPC_Franklins                     ((double)  SIPC_Franklin)
/// electrical capacity
#define	 SIPC_Farad	                        ((double)  SIPC_Coulomb/SIPC_Volt)
#define	 SIPC_Farads	                    ((double)  SIPC_Farad)
#define	 SIPC_F                             ((double)  SIPC_Farad)
/// magnetic flux
#define	 SIPC_Weber	                        ((double)  SIPC_Volt*SIPC_second)
#define	 SIPC_Webers                        ((double)  SIPC_Weber)
#define	 SIPC_Wb	                        ((double)  SIPC_Weber)
#define	 SIPC_Maxwell	                    ((double)  SIPC_Weber/100000000.0)
#define	 SIPC_Maxwells                      ((double)  SIPC_Maxwell)
#define	 SIPC_M                             ((double)  SIPC_Maxwell)
/// magnetic field B
#define	 SIPC_Tesla	                        ((double)  SIPC_Weber/(SIPC_meter*SIPC_meter))
#define	 SIPC_Teslas                        ((double)  SIPC_Tesla)
#define	 SIPC_T                             ((double)  SIPC_Tesla)
#define	 SIPC_Gauss	                        ((double)  SIPC_Tesla/10000.0)
#define	 SIPC_gamma	                        ((double)  SIPC_Tesla/1000000000.0)
/// magnetic field H
#define	 SIPC_Oerstedt                      ((double)  79.57747*SIPC_Ampere/SIPC_meter)
#define	 SIPC_Oerstedts                     ((double)  SIPC_Oerstedt)
#define	 SIPC_Oe	                        ((double)  SIPC_Oerstedt)
/// magnetic inductivity
#define	 SIPC_Henry	                        ((double)  SIPC_Weber/SIPC_Ampere)
#define	 SIPC_Henrys                        ((double)  SIPC_Henry)
#define	 SIPC_H                             ((double)  SIPC_Henry)
#define	 SIPC_milliHenry	                ((double)  SIPC_Henry/1000.0)
#define	 SIPC_milliHenrys                   ((double)  SIPC_milliHenry)
#define	 SIPC_mH                            ((double)  SIPC_milliHenry)
/// temperature
#define	 SIPC_Kelvin                        ((double)  1.0)
#define	 SIPC_Kelvins                       ((double)  SIPC_Kelvin)
#define	 SIPC_K                             ((double)  SIPC_Kelvin)
/// luminous intensity
#define	 SIPC_candela	                        ((double)  1.0)
#define	 SIPC_candelas                      ((double)  SIPC_candela)
#define	 SIPC_cd	                        ((double)  SIPC_candela)
#define	 SIPC_apostilb                      ((double)  SIPC_candelas/SIPC_meter/SIPC_meter)
#define	 SIPC_apostilbs                     ((double)  SIPC_apostilb)
#define	 SIPC_nit	                        ((double)  SIPC_apostilb)
#define	 SIPC_nits	                        ((double)  SIPC_nit)
#define	 SIPC_skot	                        ((double)  SIPC_apostilb/1000.0)
#define	 SIPC_skots	                        ((double)  SIPC_skot)
#define	 SIPC_stilb	                        ((double)  10000.0*SIPC_apostilbs)
#define	 SIPC_stilbs	                    ((double)  SIPC_stilb)
#define	 SIPC_Blondel	                    ((double)  SIPC_apostilb/SIPC_pi)
#define	 SIPC_Blondels                      ((double)  SIPC_Blondel)
#define	 SIPC_Lambert	                    ((double)  10000.0*SIPC_Blondels)
#define	 SIPC_Lamberts                      ((double)  SIPC_Lambert)
/// light flux
#define	 SIPC_lumen	                        ((double)  SIPC_candela*SIPC_steradian)
#define	 SIPC_lumens	                    ((double)  SIPC_lumen)
#define	 SIPC_lm	                        ((double)  SIPC_lumen)
/// light intensity
#define	 SIPC_lux	                        ((double)  SIPC_lumens/SIPC_meter/SIPC_meter)
#define	 SIPC_luxes	                        ((double)  SIPC_lux)
#define	 SIPC_luces	                        ((double)  SIPC_lux)
#define	 SIPC_lx	                        ((double)  SIPC_lux)
#define	 SIPC_nox	                        ((double)  SIPC_lux/1000.0)
#define	 SIPC_phot	                        ((double)  SIPC_lumens/SIPC_centimeter/SIPC_centimeter)
#define	 SIPC_phots	                        ((double)  SIPC_phot)
#define	 SIPC_equivalent_lux	            ((double)  SIPC_lux/SIPC_pi)
#define	 SIPC_equivalent_luxes	            ((double)  SIPC_equivalent_lux)
#define	 SIPC_equivalent_luces	            ((double)  SIPC_equivalent_lux)
#define	 SIPC_equivalent_lx	                ((double)  SIPC_equivalent_lux)
#define	 SIPC_equivalent_lumen	            ((double)  SIPC_lumen/SIPC_pi)
#define	 SIPC_equivalent_lumens	            ((double)  SIPC_equivalent_lumen)
#define	 SIPC_equivalent_lm	                ((double)  SIPC_equivalent_lumen)
#define	 SIPC_equivalent_phot	            ((double)  SIPC_apostilb/SIPC_pi)
#define	 SIPC_equivalent_phots	            ((double)  SIPC_equivalent_phot)
/// acceleration
#define	 SIPC_Galileo	                    ((double)  SIPC_centimeters/SIPC_second/SIPC_second)
#define	 SIPC_Galileos                      ((double)  SIPC_Galileo)
/// standard gavitational acceleration at sea level
#define	 SIPC_gravity	                    ((double)  9.80665*SIPC_meters/SIPC_second/SIPC_second)
/// mass
#define	 SIPC_kilohyl	                    ((double)  SIPC_kilogram*SIPC_gravity*SIPC_second*SIPC_second/SIPC_meter)
#define	 SIPC_kilohyls                      ((double)  SIPC_kilohyl)
#define	 SIPC_hyl	                        ((double)  SIPC_kilohyl/1000.0)
#define	 SIPC_hyls	                        ((double)  SIPC_hyl)

/// English Units
/// length
#define	 SIPC_inch	                        ((double)  0.0254*SIPC_meters)
#define	 SIPC_inches	                    ((double)  SIPC_inch)
#define	 SIPC_in	                        ((double)  SIPC_inch)
#define	 SIPC_mil	                        ((double)  SIPC_inch/1000.0)
#define	 SIPC_mils	                        ((double)  SIPC_mil)
#define	 SIPC_point	                        ((double)  SIPC_inch/72.27)
#define	 SIPC_points	                    ((double)  SIPC_point)
#define	 SIPC_pt	                        ((double)  SIPC_point)
#define	 SIPC_bottommeasure                 ((double)  SIPC_inch/40.0)
#define	 SIPC_bottommeasures	            ((double)  SIPC_bottommeasure)
#define	 SIPC_line	                        ((double)  SIPC_inch/12.0)
#define	 SIPC_lines	                        ((double)  SIPC_line)
#define	 SIPC_pica	                        ((double)  12.0*SIPC_points)
#define	 SIPC_picas	                        ((double)  SIPC_pica)
#define	 SIPC_barleycorn	                ((double)  SIPC_inch/3.0)
#define	 SIPC_barleycorns	                ((double)  SIPC_barleycorn)
#define	 SIPC_finger	                    ((double)  7.0*SIPC_inches/8.0)
#define	 SIPC_fingers                       ((double)  SIPC_finger)
#define	 SIPC_palm                          ((double)  3.0*SIPC_inches)
#define	 SIPC_palms                         ((double)  SIPC_palm)
#define	 SIPC_hand                          ((double)  4.0*SIPC_inches)
#define	 SIPC_hands                         ((double)  SIPC_hand)
#define	 SIPC_link                          ((double)  7.92*SIPC_inches)
#define	 SIPC_links                         ((double)  SIPC_link)
#define	 SIPC_li                            ((double)  SIPC_link)
#define	 SIPC_span                          ((double)  9.0*SIPC_inches)
#define	 SIPC_spans                         ((double)  SIPC_span)
#define	 SIPC_foot                          ((double)  12.0*SIPC_inches)
#define	 SIPC_feet                          ((double)  SIPC_foot)
#define	 SIPC_ft                            ((double)  SIPC_foot)
#define	 SIPC_cubit                         ((double)  18.0*SIPC_inches)
#define	 SIPC_cubits                        ((double)  SIPC_cubit)
#define	 SIPC_yard                          ((double)  3.0*SIPC_feet)
#define	 SIPC_yards                         ((double)  SIPC_yard)
#define	 SIPC_yd                            ((double)  SIPC_yard)
#define	 SIPC_nail                          ((double)  SIPC_yard/16.0)
#define	 SIPC_nails                         ((double)  SIPC_nail)
#define	 SIPC_ell                           ((double)  45.0*SIPC_inches)
#define	 SIPC_ells                          ((double)  SIPC_ell)
#define	 SIPC_pace                          ((double)  5.0*SIPC_feet)
#define	 SIPC_paces                         ((double)  SIPC_pace)
#define	 SIPC_fathom                        ((double)  6.0*SIPC_feet)
#define	 SIPC_fathoms                       ((double)  SIPC_fathom)
#define	 SIPC_fm                            ((double)  SIPC_fathom)
#define	 SIPC_rod                           ((double)  198.0*SIPC_inches)
#define	 SIPC_rods                          ((double)  SIPC_rod)
#define	 SIPC_rd                            ((double)  SIPC_rod)
#define	 SIPC_pole                          ((double)  SIPC_rod)
#define	 SIPC_poles                         ((double)  SIPC_pole)
#define	 SIPC_p                             ((double)  SIPC_pole)
#define	 SIPC_perch                         ((double)  SIPC_rod)
#define	 SIPC_perches                       ((double)  SIPC_perch)
#define	 SIPC_rope                          ((double)  20.0*SIPC_feet)
#define	 SIPC_ropes                         ((double)  SIPC_rope)
#define	 SIPC_bolt                          ((double)  40.0*SIPC_yards)
#define	 SIPC_bolts                         ((double)  SIPC_bolt)
#define	 SIPC_chain                         ((double)  4.0*SIPC_rods)
#define	 SIPC_chains                        ((double)  SIPC_chain)
#define	 SIPC_ch                            ((double)  SIPC_chain)
#define	 SIPC_gunters_chain	                ((double)  SIPC_chain)
#define	 SIPC_gunters_chains	            ((double)  SIPC_gunters_chain)
#define	 SIPC_engineers_link	            ((double)  SIPC_foot)
#define	 SIPC_engineers_links	            ((double)  SIPC_engineers_link)
#define	 SIPC_engineers_chain	            ((double)  100.0*SIPC_feet)
#define	 SIPC_engineers_chains              ((double)  SIPC_engineers_chain)
#define	 SIPC_skein                         ((double)  120*SIPC_yards)
#define	 SIPC_skeins                        ((double)  SIPC_skein)
#define	 SIPC_furlong                       ((double)  220*SIPC_yards)
#define	 SIPC_furlongs                      ((double)  SIPC_furlong)
#define	 SIPC_spindle                       ((double)  14400*SIPC_yards)
#define	 SIPC_spindles                      ((double)  SIPC_spindle)
#define	 SIPC_US_cable_length	            ((double)  120.0*SIPC_fathoms)
#define	 SIPC_US_cable_lengths	            ((double)  SIPC_US_cable_length)
#define	 SIPC_British_cable_length	        ((double)  100.0*SIPC_fathoms)
#define	 SIPC_British_cable_lengths	        ((double)  SIPC_British_cable_length)
#define	 SIPC_statute_mile	                ((double)  5280.0*SIPC_feet)
#define	 SIPC_statute_miles                 ((double)  SIPC_statute_mile)
#define	 SIPC_statute_mi	                ((double)  SIPC_statute_mile)
#define	 SIPC_statute_league	            ((double)  3.0*SIPC_statute_miles)
#define	 SIPC_statute_leagues	            ((double)  SIPC_statute_league)
#define	 SIPC_nautical_mile	                ((double)  1852*SIPC_meters)
#define	 SIPC_nautical_miles	            ((double)  SIPC_nautical_mile)
#define	 SIPC_nautical_nm                   ((double)  SIPC_nautical_mile)
#define	 SIPC_nautical_league	            ((double)  3.0*SIPC_nautical_miles)
#define	 SIPC_nautical_leagues              ((double)  SIPC_nautical_league)
#define	 SIPC_geodetic_foot	                ((double)  (1200.0/3937.0)*SIPC_meters)
#define	 SIPC_geodetic_feet	                ((double)  SIPC_geodetic_foot)
#define	 SIPC_geodetic_ft	                ((double)  SIPC_geodetic_foot)
#define	 SIPC_geographical_mile	            ((double)  SIPC_nautical_mile)
#define	 SIPC_geographical_miles	        ((double)  SIPC_geographical_mile)
#define	 SIPC_geographical_mi	            ((double)  SIPC_geographical_mile)
#define	 SIPC_parasang                      ((double)  3.5*SIPC_statute_miles)
#define	 SIPC_parasangs                     ((double)  SIPC_parasang)
#define	 SIPC_arpentcan                     ((double)  27.52*SIPC_statute_miles)
#define	 SIPC_arpentcans	                ((double)  SIPC_arpentcan)
#define	 SIPC_arpentlin                     ((double)  191.835*SIPC_feet)
#define	 SIPC_arpentlins	                ((double)  SIPC_arpentlin)
#define	 SIPC_astronomical_unit	            ((double)  1.49597871e11*SIPC_meters)
#define	 SIPC_astronomical_units	        ((double)  SIPC_astronomical_unit)
#define	 SIPC_AU                            ((double)  SIPC_astronomical_unit)
#define	 SIPC_lightyear                     ((double)  9.4605e15*SIPC_meters)
#define	 SIPC_lightyears	                ((double)  SIPC_lightyear)
#define	 SIPC_ly                            ((double)  SIPC_lightyear)
#define	 SIPC_parsec                        ((double)  SIPC_AU*SIPC_radians/SIPC_arc_second)
#define	 SIPC_parsecs                       ((double)  SIPC_parsec)
#define	 SIPC_pc                            ((double)  SIPC_parsec)
/// area
#define	 SIPC_barn                          ((double)  1.0e-28*SIPC_meter*SIPC_meter)
#define	 SIPC_barns                         ((double)  SIPC_barn)
#define	 SIPC_b                             ((double)  SIPC_barn)
#define	 SIPC_circular_inch                 ((double)  0.25*SIPC_pi*SIPC_inch*SIPC_inch)
#define	 SIPC_circular_inches	            ((double)  SIPC_circular_inch)
#define	 SIPC_circular_mil	                ((double)  0.25*SIPC_pi*SIPC_mil*SIPC_mil)
#define	 SIPC_circular_mils	                ((double)  SIPC_circular_mil)
#define	 SIPC_sabin                         ((double)  SIPC_foot*SIPC_foot)
#define	 SIPC_sabins                        ((double)  SIPC_sabin)
#define	 SIPC_square                        ((double)  100.0*SIPC_sabin)
#define	 SIPC_squares                       ((double)  SIPC_square)
#define	 SIPC_are                           ((double)  100.0*SIPC_meter*SIPC_meter)
#define	 SIPC_ares                          ((double)  SIPC_are)
#define	 SIPC_a                             ((double)  SIPC_are)
#define	 SIPC_rood                          ((double)  40.0*SIPC_rod*SIPC_rod)
#define	 SIPC_roods                         ((double)  SIPC_rood)
#define	 SIPC_ro                            ((double)  SIPC_rood)
#define	 SIPC_acre                          ((double)  4.0*SIPC_roods)
#define	 SIPC_acres                         ((double)  SIPC_acre)
#define	 SIPC_section                       ((double)  SIPC_statute_mile*SIPC_statute_mile)
#define	 SIPC_sections                      ((double)  SIPC_section)
#define	 SIPC_homestead                     ((double)  SIPC_section/4.0)
#define	 SIPC_homesteads	                ((double)  SIPC_homestead)
#define	 SIPC_township                      ((double)  36.0*SIPC_sections)
#define	 SIPC_townships                     ((double)  SIPC_township)
/// volume
#define	 SIPC_minim                         ((double)  6.161152e-8*(m*SIPC_m*SIPC_m))
#define	 SIPC_minims                        ((double)  SIPC_minim)
#define	 SIPC_drop                          ((double)  0.03*SIPC_cc)
#define	 SIPC_drops                         ((double)  SIPC_drop)
#define	 SIPC_teaspoon                      ((double)  4.928922*SIPC_cc)
#define	 SIPC_teaspoons                     ((double)  SIPC_teaspoon)
#define	 SIPC_tablespoon	                ((double)  3.0*SIPC_teaspoons)
#define	 SIPC_tablespoons                   ((double)  SIPC_tablespoon)
#define	 SIPC_US_liquid_dram	            ((double)  60.0*SIPC_minims)
#define	 SIPC_US_liquid_drams               ((double)  SIPC_US_liquid_dram)
#define	 SIPC_US_liquid_dr	                ((double)  SIPC_US_liquid_dram)
#define	 SIPC_US_liquid_ounce	            ((double)  8.0*SIPC_US_liquid_drams)
#define	 SIPC_US_liquid_ounces              ((double)  SIPC_US_liquid_ounce)
#define	 SIPC_US_liquid_oz	                ((double)  SIPC_US_liquid_ounce)
#define	 SIPC_US_liquid_gill	            ((double)  4.0*SIPC_US_liquid_ounces)
#define	 SIPC_US_liquid_gills	            ((double)  SIPC_US_liquid_gill)
#define	 SIPC_US_liquid_gl	                ((double)  SIPC_US_liquid_gill)
#define	 SIPC_US_liquid_pint	            ((double)  4.0*SIPC_US_liquid_gills)
#define	 SIPC_US_liquid_pints               ((double)  SIPC_US_liquid_pint)
#define	 SIPC_US_liquid_pt	                ((double)  SIPC_US_liquid_pint)
#define	 SIPC_US_liquid_quart	            ((double)  2.0*SIPC_US_liquid_pints)
#define	 SIPC_US_liquid_quarts	            ((double)  SIPC_US_liquid_quart)
#define	 SIPC_US_liquid_qt                  ((double)  SIPC_US_liquid_quart)
#define	 SIPC_US_liquid_magnum	            ((double)  2.0*SIPC_US_liquid_quarts)
#define	 SIPC_US_liquid_magnums             ((double)  SIPC_US_liquid_magnum)
#define	 SIPC_US_liquid_gallon              ((double)  4.0*SIPC_US_liquid_quarts)
#define	 SIPC_US_liquid_gallons             ((double)  SIPC_US_liquid_gallon)
#define	 SIPC_US_liquid_gal	                ((double)  SIPC_US_liquid_gallon)
#define	 SIPC_US_dry_pint	                ((double)  550.61047*SIPC_cc)
#define	 SIPC_US_dry_pints	                ((double)  SIPC_US_dry_pint)
#define	 SIPC_US_dry_pt                     ((double)  SIPC_US_dry_pint)
#define	 SIPC_US_dry_quart	                ((double)  2.0*SIPC_US_dry_pints)
#define	 SIPC_US_dry_quarts	                ((double)  SIPC_US_dry_quart)
#define	 SIPC_US_dry_qt                     ((double)  SIPC_US_dry_quart)
#define	 SIPC_US_peck                       ((double)  8.0*SIPC_US_dry_quarts)
#define	 SIPC_US_pecks                      ((double)  SIPC_US_peck)
#define	 SIPC_US_pk                         ((double)  SIPC_US_peck)
#define	 SIPC_US_bushel                     ((double)  4.0*SIPC_US_pecks)
#define	 SIPC_US_bushels	                ((double)  SIPC_US_bushel)
#define	 SIPC_US_bu                         ((double)  SIPC_US_bushel)
#define	 SIPC_US_barrel                     ((double)  31.5*SIPC_US_liquid_gallons)
#define	 SIPC_US_barrels                    ((double)  SIPC_US_barrel)
#define	 SIPC_US_bbl                        ((double)  SIPC_US_barrel)
#define	 SIPC_US_bl                         ((double)  SIPC_US_barrel)
#define	 SIPC_British_fluid_drachm	        ((double)  60.0*SIPC_minims)
#define	 SIPC_British_fluid_drachms	        ((double)  SIPC_British_fluid_drachm)
#define	 SIPC_British_fluid_dr	            ((double)  SIPC_British_fluid_drachm)
#define	 SIPC_British_fluid_ounce	        ((double)  8.0*SIPC_British_fluid_drachms)
#define	 SIPC_British_fluid_ounces	        ((double)  SIPC_British_fluid_ounce)
#define	 SIPC_British_fluid_oz	            ((double)  SIPC_British_fluid_ounce)
#define	 SIPC_British_fluid_gill	        ((double)  5.0*SIPC_British_fluid_ounces)
#define	 SIPC_British_fluid_gills	        ((double)  SIPC_British_fluid_gill)
#define	 SIPC_British_fluid_gi	            ((double)  SIPC_British_fluid_gill)
#define	 SIPC_British_fluid_pint	        ((double)  4.0*SIPC_British_fluid_gills)
#define	 SIPC_British_fluid_pints	        ((double)  SIPC_British_fluid_pint)
#define	 SIPC_British_fluid_pt	            ((double)  SIPC_British_fluid_pint)
#define	 SIPC_British_fluid_quart	        ((double)  2.0*SIPC_British_fluid_pints)
#define	 SIPC_British_fluid_quarts          ((double)  SIPC_British_fluid_quart)
#define	 SIPC_British_fluid_qt              ((double)  SIPC_British_fluid_quart)
#define	 SIPC_British_fluid_gallon	        ((double)  4.0*SIPC_British_fluid_quarts)
#define	 SIPC_British_fluid_gallons	        ((double)  SIPC_British_fluid_gallon)
#define	 SIPC_British_fluid_gal	            ((double)  SIPC_British_fluid_gallon)
#define	 SIPC_British_peck                  ((double)  2.0*SIPC_British_fluid_gallons)
#define	 SIPC_British_pecks	                ((double)  SIPC_British_peck)
#define	 SIPC_British_pk	                ((double)  SIPC_British_peck)
#define	 SIPC_British_bushel                ((double)  4.0*SIPC_British_pecks)
#define	 SIPC_British_bushels	            ((double)  SIPC_British_bushel)
#define	 SIPC_British_bu	                ((double)  SIPC_British_bushel)
#define	 SIPC_British_barrel	            ((double)  36.0*SIPC_British_fluid_gallons)
#define	 SIPC_British_barrels	            ((double)  SIPC_British_barrel)
#define	 SIPC_British_bbl                   ((double)  SIPC_British_barrel)
#define	 SIPC_British_bl	                ((double)  SIPC_British_barrel)
#define	 SIPC_noggin                        ((double)  SIPC_2.0*SIPC_US_liquid_ounces)
#define	 SIPC_noggins                       ((double)  SIPC_noggin)
#define	 SIPC_cup                           ((double)  8.0*SIPC_US_liquid_ounces)
#define	 SIPC_cups                          ((double)  SIPC_cup)
#define	 SIPC_fifth                         ((double)  SIPC_US_liquid_gallon/5.0)
#define	 SIPC_fifths                        ((double)  SIPC_fifth)
#define	 SIPC_jeroboam                      ((double)  4.0*SIPC_fifths)
#define	 SIPC_jeroboams                     ((double)  SIPC_jeroboam)
#define	 SIPC_firkin                        ((double)  9.0*SIPC_US_liquid_gallons)
#define	 SIPC_firkins                       ((double)  SIPC_firkin)
#define	 SIPC_kilderkin                     ((double)  18.0*SIPC_US_liquid_gallons)
#define	 SIPC_kilderkins	                ((double)  SIPC_kilderkin)
#define	 SIPC_strike                        ((double)  2.0*SIPC_US_bushels)
#define	 SIPC_strikes                       ((double)  SIPC_strike)
#define	 SIPC_sack                          ((double)  3.0*SIPC_US_bushels)
#define	 SIPC_sacks                         ((double)  SIPC_sack)
#define	 SIPC_coomb                         ((double)  4.0*SIPC_US_bushels)
#define	 SIPC_coombs                        ((double)  SIPC_coomb)
#define	 SIPC_seam                          ((double)  8.0*SIPC_US_bushels)
#define	 SIPC_seams                         ((double)  SIPC_seam)
#define	 SIPC_wey                           ((double)  40.0*SIPC_US_bushels)
#define	 SIPC_weys                          ((double)  SIPC_wey)
#define	 SIPC_last                          ((double)  80.0*SIPC_US_bushels)
#define	 SIPC_lasts                         ((double)  SIPC_last)
#define	 SIPC_register_ton	                ((double)  100.0*SIPC_(ft*SIPC_ft*SIPC_ft))
#define	 SIPC_register_tons                 ((double)  SIPC_register_ton)
#define	 SIPC_register_tn	                ((double)  SIPC_register_ton)
#define	 SIPC_cord                          ((double)  128.0*(ft*SIPC_ft*SIPC_ft))
#define	 SIPC_cords                         ((double)  SIPC_cord)
#define	 SIPC_cordfoot                      ((double)  SIPC_cord)
#define	 SIPC_cordfeet                      ((double)  SIPC_cordfoot)
#define	 SIPC_boardfoot                     ((double)  144.0*SIPC_inch*SIPC_inch*SIPC_inch)
#define	 SIPC_boardfeet                     ((double)  SIPC_boardfoot)
#define	 SIPC_timberfoot                    ((double)  SIPC_foot*SIPC_foot*SIPC_foot)
#define	 SIPC_timberfeet	                ((double)  SIPC_timberfoot)
#define	 SIPC_hogshead                      ((double)  2.0*SIPC_US_barrels)
#define	 SIPC_hogsheads                     ((double)  SIPC_hogshead)
#define	 SIPC_pipe                          ((double)  4.0*SIPC_US_barrels)
#define	 SIPC_pipes                         ((double)  SIPC_pipe)
#define	 SIPC_tun                           ((double)  8.0*SIPC_US_barrels)
#define	 SIPC_tuns                          ((double)  SIPC_tun)
/// mass
#define	 SIPC_grain                         ((double)  0.06479891*SIPC_grams)
#define	 SIPC_grains                        ((double)  SIPC_grain)
#define	 SIPC_gr                            ((double)  SIPC_grain)
#define	 SIPC_pennyweight	                ((double)  24.0*SIPC_grains)
#define	 SIPC_dwt                           ((double)  SIPC_pennyweight)
/// apothecary weight
#define	 SIPC_apothecary_scruple            ((double)  20.0*SIPC_grains)
#define	 SIPC_apothecary_scruples	        ((double)  SIPC_apothecary_scruple)
#define	 SIPC_apothecary_s	                ((double)  SIPC_apothecary_scruple)
#define	 SIPC_apothecary_dram	            ((double)  3.0*SIPC_apothecary_scruples)
#define	 SIPC_apothecary_drams	            ((double)  SIPC_apothecary_dram)
#define	 SIPC_apothecary_dr	                ((double)  SIPC_apothecary_dram)
#define	 SIPC_apothecary_ounce	            ((double)  8.0*SIPC_apothecary_drams)
#define	 SIPC_apothecary_ounces	            ((double)  SIPC_apothecary_ounce)
#define	 SIPC_apothecary_oz	                ((double)  SIPC_apothecary_ounce)
#define	 SIPC_apothecary_pound	            ((double)  12.0*SIPC_apothecary_ounces)
#define	 SIPC_apothecary_pounds	            ((double)  SIPC_apothecary_pound)
#define	 SIPC_apothecary_lb	                ((double)  SIPC_apothecary_pound)

#define	 SIPC_troy_scruple	                ((double)  20.0*SIPC_grains)
#define	 SIPC_troy_scruples	                ((double)  SIPC_troy_scruple)
#define	 SIPC_troy_s                        ((double)  SIPC_troy_scruple)
#define	 SIPC_troy_dram                     ((double)  3.0*SIPC_troy_scruples)
#define	 SIPC_troy_drams	                ((double)  SIPC_troy_dram)
#define	 SIPC_troy_dr                       ((double)  SIPC_troy_dram)
#define	 SIPC_troy_ounce	                ((double)  8.0*SIPC_troy_drams)
#define	 SIPC_troy_ounces	                ((double)  SIPC_troy_ounce)
#define	 SIPC_troy_oz                       ((double)  SIPC_troy_ounce)
#define	 SIPC_troy_pound	                ((double)  12.0*SIPC_troy_ounces)
#define	 SIPC_troy_pounds	                ((double)  SIPC_troy_pound)
#define	 SIPC_troy_lb                       ((double)  SIPC_troy_pound)

#define	 SIPC_avoirdupois_pound	            ((double)  7000.0*SIPC_grains)
#define	 SIPC_avoirdupois_pounds	        ((double)  SIPC_avoirdupois_pound)
#define	 SIPC_avoirdupois_lb	            ((double)  SIPC_avoirdupois_pound)
#define	 SIPC_avoirdupois_ounce	            ((double)  SIPC_avoirdupois_pound/16.0)
#define	 SIPC_avoirdupois_ounces	        ((double)  SIPC_avoirdupois_ounce)
#define	 SIPC_avoirdupois_oz	            ((double)  SIPC_avoirdupois_ounce)
#define	 SIPC_avoirdupois_dram	            ((double)  SIPC_avoirdupois_ounce/16.0)
#define	 SIPC_avoirdupois_drams             ((double)  SIPC_avoirdupois_dram)
#define	 SIPC_avoirdupois_dr	            ((double)  SIPC_avoirdupois_dram)
#define	 SIPC_stone                         ((double)  14.0*SIPC_avoirdupois_pounds)
#define	 SIPC_stones                        ((double)  SIPC_avoirdupois_stone)
#define	 SIPC_st                            ((double)  SIPC_avoirdupois_stone)
#define	 SIPC_US_hundredweight	            ((double)  100.0*SIPC_avoirdupois_pounds)
#define	 SIPC_US_cwt                        ((double)  SIPC_US_hundredweight)
#define	 SIPC_US_quarter                    ((double)  SIPC_US_hundredweight/4.0)
#define	 SIPC_US_quarters                   ((double)  SIPC_US_quarter)
#define	 SIPC_US_qr                         ((double)  SIPC_US_quarter)
#define	 SIPC_US_ton                        ((double)  20.0*SIPC_US_hundredweight)
#define	 SIPC_US_tons                       ((double)  SIPC_US_ton)
#define	 SIPC_US_tn                         ((double)  SIPC_US_ton)
#define	 SIPC_US_deadweight	                ((double)  SIPC_US_ton)

#define	 SIPC_British_hundredweight         ((double)  112.0*SIPC_avoirdupois_pounds)
#define	 SIPC_British_cwt                   ((double)  SIPC_British_hundredweight)
#define	 SIPC_British_quarter	            ((double)  SIPC_British_hundredweight/4.0)
#define	 SIPC_British_quarters	            ((double)  SIPC_British_quarter)
#define	 SIPC_British_qr                    ((double)  SIPC_British_quarter)
#define	 SIPC_British_ton	                ((double)  20.0*SIPC_British_hundredweight)
#define	 SIPC_British_tons	                ((double)  SIPC_British_ton)
#define	 SIPC_British_tn	                ((double)  SIPC_British_ton)

#define	 SIPC_Imperial_hundredweight	    ((double)  112.0*SIPC_avoirdupois_pounds)
#define	 SIPC_Imperial_cwt	                ((double)  SIPC_Imperial_hundredweight)
#define	 SIPC_Imperial_quarter	            ((double)  SIPC_Imperial_hundredweight/4.0)
#define	 SIPC_Imperial_quarters	            ((double)  SIPC_Imperial_quarter)
#define	 SIPC_Imperial_qr                   ((double)  SIPC_Imperial_quarter)
#define	 SIPC_Imperial_ton	                ((double)  20.0*SIPC_Imperial_hundredweight)
#define	 SIPC_Imperial_tons	                ((double)  SIPC_Imperial_ton)
#define	 SIPC_Imperial_tn	                ((double)  SIPC_Imperial_ton)
#define	 SIPC_crith                         ((double)  0.0906*SIPC_grams)
#define	 SIPC_criths                        ((double)  SIPC_crith)
#define	 SIPC_bag                           ((double)  94.0*SIPC_avoirdupois_pounds)
#define	 SIPC_bags                          ((double)  SIPC_bag)
#define	 SIPC_cental                        ((double)  100.0*SIPC_avoirdupois_pounds)
#define	 SIPC_centals                       ((double)  SIPC_cental)
#define	 SIPC_weymass                       ((double)  252.0*SIPC_avoirdupois_pounds)
/// rate
#define	 SIPC_mgd                           ((double)  1000000.0*SIPC_US_liquid_gallons/SIPC_day)
#define	 SIPC_cfs                           ((double)  SIPC_foot*SIPC_foot*SIPC_foot/SIPC_second)
#define	 SIPC_minersinch	                ((double)  1.5*SIPC_foot*SIPC_foot*SIPC_foot/SIPC_minute)
#define	 SIPC_mpg                           ((double)  SIPC_statute_miles/US_liquid_gallon)
/// speed
#define	 SIPC_mph                           ((double)  SIPC_statute_miles/SIPC_hour)
#define	 SIPC_knot                          ((double)  SIPC_nautical_miles/SIPC_hour)
#define	 SIPC_knots                         ((double)  SIPC_knot)
#define	 SIPC_admiralty_knot	            ((double)  6980.0*SIPC_feet/SIPC_hour)
#define	 SIPC_admiralty_knots               ((double)  SIPC_admiralty_knot)
/// force
#define	 SIPC_poundal                       ((double)  SIPC_avdp_pound*SIPC_foot/(second*SIPC_second))
#define	 SIPC_poundals                      ((double)  SIPC_poundal)
#define	 SIPC_pdl                           ((double)  SIPC_poundal)
#define	 SIPC_lbf                           ((double)  SIPC_avoirdupois_pound*SIPC_gravity)
/// pressure
#define	 SIPC_psi                           ((double)  SIPC_lbf/(inch*SIPC_inch))
/// energy
#define	 SIPC_calorie                       ((double)  4.1868*SIPC_Joules)
#define	 SIPC_calories                      ((double)  SIPC_calorie)
#define	 SIPC_cal                           ((double)  SIPC_calorie)
#define	 SIPC_kilocalorie	                ((double)  1000.0*SIPC_calories)
#define	 SIPC_kilocalories	                ((double)  SIPC_kilocalorie)
#define	 SIPC_kcal                          ((double)  SIPC_kilocalorie)
#define	 SIPC_Frigorie                      ((double)  SIPC_kilocalorie)
#define	 SIPC_Frigories                     ((double)  SIPC_Frigorie)
#define	 SIPC_Btu                           ((double)  1055.06*SIPC_Joules)
#define	 SIPC_therm                         ((double)  10000.0*SIPC_Btu)
#define	 SIPC_therms                        ((double)  SIPC_therm)
#define	 SIPC_thermie                       ((double)  1000000.0*SIPC_calories)
#define	 SIPC_thermies                      ((double)  SIPC_thermie)
/// power
#define	 SIPC_horsepower                    ((double)  735.49875*SIPC_Watts)
#define	 SIPC_HP                            ((double)  SIPC_horsepower)
/// electrical current
#define	 SIPC_Gilbert                       ((double)  0.795775*SIPC_Amperes)
#define	 SIPC_Gilberts                      ((double)  SIPC_Gilbert)
/// temperature
#define	 SIPC_Rankin                        ((double)  1.8*SIPC_Kelvins)
#define	 SIPC_Rankins                       ((double)  SIPC_Rankin)
#define	 SIPC_R                             ((double)  SIPC_Rankin)
/// luminous intensity
#define	 SIPC_candle                        ((double)  1.02*SIPC_candelas)
#define	 SIPC_candles                       ((double)  SIPC_candle)
#define	 SIPC_Hefner_candle	                ((double)  0.9*SIPC_candles)
#define	 SIPC_Hefner_candles	            ((double)  SIPC_Hefner_candle)
/// light intensity
#define	 SIPC_foot_candle	                ((double)  SIPC_lumens/SIPC_foot/SIPC_foot)
#define	 SIPC_foot_candles	                ((double)  SIPC_foot_candle)
#define	 SIPC_fc                            ((double)  SIPC_foot_candle)
#define	 SIPC_foot_Lambert	                ((double)  SIPC_candelas/SIPC_foot/SIPC_foot/SIPC_pi)
#define	 SIPC_foot_Lamberts	                ((double)  SIPC_foot_Lambert)
#define	 SIPC_equivalent_foot_candle	    ((double)  SIPC_foot_candle/SIPC_pi)
#define	 SIPC_equivalent_foot_candles	    ((double)  SIPC_equivalent_foot_candle)
#define	 SIPC_equivalent_fc	                ((double)  SIPC_equivalent_foot_candle)

    /// speed of light
#define	 SIPC_c                             ((double)  2.99792458e8*SIPC_meters/SIPC_second)
    /// speed of sound
#define	 SIPC_Mach                          ((double)  331.46*SIPC_meters/SIPC_second)
    /// Planck constant
#define	 SIPC_h                             ((double)  6.6260755e-34*SIPC_Joule*SIPC_seconds)
#define	 SIPC_h_bar                         ((double)  SIPC_h/(2.0*SIPC_pi))
    /// standard gavitational acceleration at sea level
#define	 SIPC_g                             ((double)  SIPC_gravity)
    /// electron charge
#define	 SIPC_e                             ((double)  1.60217733e-19*SIPC_Coulombs)
    /// elevtron Volt
#define	 SIPC_eV                            ((double)  SIPC_e*SIPC_V)
#define	 SIPC_keV                           ((double)  1000.0*SIPC_eV)
#define	 SIPC_MeV                           ((double)  1000000.0*SIPC_eV)
#define	 SIPC_GeV                           ((double)  1000000000.0*SIPC_eV)
#define	 SIPC_Rydberg                       ((double)  13.6054*SIPC_eV)
#define	 SIPC_Rydbergs                      ((double)  SIPC_Rydberg)
    /// electron mass
#define	 SIPC_m_e                           ((double)  9.1093897e-31*SIPC_kilograms)
    /// proton mass
#define	 SIPC_m_P                           ((double)  1.6726231e-27*SIPC_kilograms)
    /// deuteron mass
#define	 SIPC_m_D                           ((double)  1875.61339*SIPC_MeV/(c*SIPC_c))
    /// unified atomic mass unit
#define SIPC_atomic_mass_unit	            ((double)  1.6605402e-27*SIPC_kilograms)
#define SIPC_atomic_mass_units	            ((double)  SIPC_atomic_mass_unit)
#define	 SIPC_amu                           ((double)  SIPC_atomic_mass_unit)
#define	 SIPC_Dalton                        ((double)  SIPC_atomic_mass_unit)
#define	 SIPC_Daltons                       ((double)  SIPC_Dalton)
    /// permittivity of free space
#define	 SIPC_epsilon                       ((double)  8.854187817e-12*SIPC_Farads/SIPC_meter)
    /// permeability of free space
#define	 SIPC_mu                            ((double)  12.566370614e-7*SIPC_Newtons/(A*SIPC_A))
    /// fine-structure constant
#define	 SIPC_alpha                         ((double)  1.0/137.0359895)
    /// classical electron radius
#define	 SIPC_r_e                           ((double)  2.81794092e-15*SIPC_meters)
    /// electron Compton wavelength
#define	 SIPC_lambda_bar                    ((double)  3.86159323e-13*SIPC_meters)
    /// Bohr radius
#define	 SIPC_a_0                           ((double)  0.529177249e-10*SIPC_meters)
    /// wavelength of 1 eV/c particle
#define	 SIPC_lambda_1eV	                ((double)  1.23984244e-6*SIPC_meters)
    /// Thomson cross section
#define	 SIPC_sigma_0                       ((double)  0.66524616*SIPC_barns)
    /// Bohr magneton
#define	 SIPC_mu_B                          ((double)  5.78838263e-11*SIPC_MeV/SIPC_Tesla)
    /// nuclear magneton
#define	 SIPC_mu_N                          ((double)  3.15245166e-14*SIPC_MeV/SIPC_Tesla)
    /// electron cyclotron frequency/field
#define	 SIPC_E_M_e                         ((double)  1.75881962e11*SIPC_C/SIPC_kg*SIPC_(rad/(s*SIPC_T)))
    /// proton cyclotron frequency/field
#define	 SIPC_E_M_P                         ((double)  9.5788309e7*SIPC_C/SIPC_kg*SIPC_(rad/(s*SIPC_T)))
    /// gravitational constant
#define	 SIPC_G                             ((double)  6.67259e-11*SIPC_m*SIPC_m*SIPC_m/(kg*SIPC_s*SIPC_s))
    /// Avogadro's constant
#define	 SIPC_N_A                           ((double)  6.0221367e23)
    /// Boltzmann constant
#define	 SIPC_K_B                           ((double)  1.380658e-23*SIPC_Joules/SIPC_Kelvin)
    /// molar volume, ideal gas at standard temperature and pressure
#define	 SIPC_V_molar                       ((double)  2.897756e-3*SIPC_meter*SIPC_Kelvins)
    /// Stefan-Boltzmann constant
#define	 SIPC_sigma_SB                      ((double)  5.67051e-8*SIPC_W/(m*SIPC_m*SIPC_K*SIPC_K*SIPC_K*SIPC_K))
    ///

#endif
