#!/bin/sh
CONFIG_LIBS="-L/usr/local/dstl/lib -lSIlib2 -L/usr/local/Cellar/gdal/1.11.5_3/lib -lgdal -lreadline -lexpat -lfftw3f -lfftw3f_threads"
CONFIG_CFLAGS="-I/usr/local/dstl/include -DSILIB2_HAVE_GDAL"
CONFIG_VERSION="2.2.1"
CONFIG_PREFIX="/usr/local/dstl"
CONFIG_GDAL="YES"

usage()
{
        cat <<EOF
Usage: SIlib2-config [OPTIONS]
Options:
        [--libs]
        [--cflags]
        [--version]
        [--gdal]
        [--prefix]
EOF
        exit $1
}

if test $# -eq 0; then
        usage 1 1>&2
fi

case $1 in 
  --libs)
    echo $CONFIG_LIBS
    ;;

  --cflags)
    echo $CONFIG_CFLAGS
    ;;

  --version)
    echo $CONFIG_VERSION
    ;;

  --gdal)
    echo $CONFIG_GDAL
    ;;

  --prefix)
    echo $CONFIG_PREFIX
    ;;

  *)
    usage 1 1>&2
    ;;

esac
