#!/bin/sh
CONFIG_LIBS="-L../lib -lsarclib -L/usr/local/Cellar/gdal/2.3.0/lib -lgdal -lreadline -lexpat -lfftw3f -lfftw3f_threads"
CONFIG_CFLAGS="-I../include -Dsarclib_HAVE_GDAL"
CONFIG_VERSION=""
CONFIG_PREFIX="../"
CONFIG_GDAL="YES"

usage()
{
        cat <<EOF
Usage: sarclib-config [OPTIONS]
Options:
        [--libs]
        [--cflags]
        [--version]
        [--gdal]
        [--prefix]
EOF
        exit $1
}

if test $# -eq 0; then
        usage 1 1>&2
fi

case $1 in 
  --libs)
    echo $CONFIG_LIBS
    ;;

  --cflags)
    echo $CONFIG_CFLAGS
    ;;

  --version)
    echo $CONFIG_VERSION
    ;;

  --gdal)
    echo $CONFIG_GDAL
    ;;

  --prefix)
    echo $CONFIG_PREFIX
    ;;

  *)
    usage 1 1>&2
    ;;

esac
