#ifdef MATERIALISE_REVISION
#undef MATERIALISE_REVISION
#endif
#ifdef MATERIALISE_SHORT_VERSION
#undef MATERIALISE_SHORT_VERSION
#endif
#ifdef MATERIALISE_FULL_VERSION
#undef MATERIALISE_FULL_VERSION
#endif
#ifdef MATERIALISE_VERSION_DATE
#undef MATERIALISE_VERSION_DATE
#endif
#define MATERIALISE_REVISION "142"
#define MATERIALISE_SHORT_VERSION "2.1.2"
#define MATERIALISE_FULL_VERSION "2.1.2-74-dc40778-dirty"
#define MATERIALISE_VERSION_DATE "2017-05-18 19:57:59 +0100"
